### ISSUE TITLE
Truck broken

### ISSUE THREAD

**Issue by iuhairways** [NVB9ALT/Addon-Aircraft-and-Parts#1]
![image](https://user-images.githubusercontent.com/103064103/197404407-27e02a6e-04ce-4dc6-ac97-412b9672181e.png)

**Comment by NVB9ALT** [comment]
I know, I saw that myself. That mod is going to require a LOT more work before it's usable - I still need to adjust the CG somehow.

**Comment by iuhairways** [comment]
okay
