### ISSUE TITLE
Boeing 737-200 is not done?

### ISSUE THREAD

**Issue by BlueWacki** [NVB9ALT/Addon-Aircraft-and-Parts#2]

**Comment by NVB9ALT** [comment]
I haven't started making the 732, I will once I release the F-117.

**Comment by Ariakim-Taiyo** [comment]
Meanwhile in another plane of existence apparently: https://geofs.fandom.com/wiki/Boeing_737-200

**Comment by BlueWacki** [comment]
how to get the 737-200?

**Comment by BlueWacki** [comment]
is here the 737-200
