### ISSUE TITLE
Site cannot be reached

### ISSUE THREAD

**Issue by RawrMachine21** [NVB9ALT/Addon-Aircraft-and-Parts#6]
So I did the realism pack and it worked beautifully, but when I click aircraft addon, it will change the site to the infamous "this site cannot be reached" page. What do I do if that happens?

**Comment by NVB9ALT** [comment]
To be clear - this happens when you attempt to load any addon aircraft from the aircraft menu?

**Comment by RawrMachine21** [comment]
no it happens when i click realism pack then click addon pack. like it wont even load geofs when i click addons

**Comment by NVB9ALT** [comment]
I think the realism pack includes the addon aircraft built-in now? that might cause issues idk

**Comment by RawrMachine21** [comment]
OMG I SEE THEM I DIDNT SCROLL DOWN ENOUGH TYSM
